<?xml version="1.0" encoding="UTF-8"?>

<suite name="Opencart test suite">


	<test name="Opencart Tests">
		
		<parameter name="browser" value="chrome" />
		<classes>
			 <class name="testCases.TestCase_NewCustomer" /> 
			  <class name="testCases.TestCase_SearchAndOrderProduct"/> 
			 <class name="testCases.TestCase_CurrencyDisplayed"/>
			
		</classes>
	</test>
	
</suite>
